### ISSUE TITLE
Formulario de feedback

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/presupuesto#5]
- [ ] Poner un link en el footer con la leyenda "¿Encontraste un error?" y que al clickearlo despliegue un formulario.
- [ ] El formulario tendrá dos campos: un `select` para describir el tipo de error (podría ser "problema", "mejora", etc) y un `textarea` donde se pueda describir el problema.
- [ ] Al hacer _submit_ del formulario podríamos recolectar información como por ejemplo el ID del `MyBudget` (si hubiera) para tener un poco más de contexto del problema.
- [ ] Hay que hacer un API endpoint que colecte esta información y la guarde como documento de una colección de MongoDB.

**Comment by fvilledary** [comment]
Y si usamos alguno de los servicios ya existentes para esto?

**Comment by jfresco** [comment]
Totalmente de acuerdo. ¿Pero estás de acuerdo en incluir este tipo de widget?

**Comment by fvilledary** [comment]
Si, por lo menos en esta etapa de pruebas me parece lo mejor. Cuando lo
lancemos oficialmente lo sacamos.
